Feature/add logger
SmarterApp/SS_SharedCode pull request #6
Opened 2017-03-08 18:19 UTC by mtrupkin

2017-03-08 20:20 UTC, jtreuting requested changes
small thing plus some questions

2017-03-08 20:20 UTC, jtreuting commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +    if (null != checkpoint && !checkpoint.isEmpty()) {
We've been using apache commons `StringUtils.isEmpty()` and `StringUtils.isNotEmpty()` for these checks

2017-03-08 20:20 UTC, jtreuting commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +      logger.warn(marker, format("exception occurred while logging event: %s", event), e);
Should this be `error`?

2017-03-08 20:20 UTC, jtreuting commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +    switch (checkpoint) {
Should this be the `Checkpoint` enum instead of a string?

2017-03-08 21:26 UTC, millerts approved these changes

2017-03-08 21:26 UTC, millerts commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +  private static final ObjectWriter writer = new ObjectMapper().writer();
I don't know if this is important or not, but the default object mapper doesn't handle Joda nor Guava fields very well.  

If this wasn't static and instead injected via Spring it could use whatever the applications object mapper's configuration is using.  That would be a pretty major overhaul of this heavily static application flow.

2017-03-08 21:29 UTC, mtrupkin commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +      logger.warn(marker, format("exception occurred while logging event: %s", event), e);
I liked the following write-up on logging levels: http://stackoverflow.com/questions/7839565/logging-levels-logback-rule-of-thumb-to-assign-log-levels

For this method, if something weird happened, the overall system is still functional.

2017-03-08 21:30 UTC, millerts reviewed
""

2017-03-08 21:34 UTC, trapnine commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +    switch (checkpoint) {
Ideally, yes, but I wanted checkpoint to be free-form text so it's easy to create arbitrary checkpoints from the application code (there's an example with EXAM_PAUSE in student app). 
Also the way I did the enum inheritance breaks switch statements (it was a switch on an enum before I made it a string and added that inheritance). I could change it to an if-else and then match against enum.name(), which would get rid of the case statement magic values.

2017-03-08 21:38 UTC, mtrupkin commented on src/main/java/org/opentestsystem/delivery/logging/EventLogger.java
> +  private static final ObjectWriter writer = new ObjectMapper().writer();
Its a good point.  We haven't serialized types from those packages yet.  So far the functions have been stateless.  We may have to refactor the class to inject the json writer.

2017-03-10 17:42 UTC, mtrupkin commented
Researching alternate approach to event logging in the feature/event-interceptor branch.
Looking to inspect the http request/response in order to determine the event type and event specific data.

2017-03-10 17:42 UTC, closed without merging